# Generated by Django 4.2.1 on 2023-06-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
