# Generated by Django 4.2.1 on 2023-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='avatar',
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
