# Generated by Django 4.2.2 on 2023-07-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
        ('blog', '0003_user_avatar_profile'),
    ]

    operations = [
    ]
