# Generated by Django 4.2.1 on 2023-07-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_0003_profile_0003_user_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
