# Generated by Django 4.2.1 on 2023-06-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='Type',
        ),
    ]
