# Generated by Django 4.2.1 on 2023-06-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_type_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.CharField(max_length=100)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.maincategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
