# Generated by Django 4.2.1 on 2023-06-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_maincategory_subcategory_remove_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='decription',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='MainCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.maincategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='SubCategory',
            field=models.CharField(max_length=100),
        ),
    ]
