# Generated by Django 4.2.1 on 2023-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='MainCategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='blog.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
