# Generated by Django 4.2.1 on 2023-06-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_remove_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
