# Generated by Django 4.2.1 on 2023-06-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_maincategory_remove_subcategory_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
