# Generated by Django 4.2.1 on 2023-06-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
